### ISSUE TITLE
Sidebar priority

### ISSUE THREAD

**Issue by millie** [activeadmin-plugins/active_admin_scoped_collection_actions#32]
I'm waiting to move the batch_actions sidebar to the top of my sidebars. Right now it hangs out very low on the page after a few other sidebar / filter situations I have going on. Is there a way to set the priority of the sidebar?

**Comment by workgena** [comment]
I don't think we will add this feature

@millie you can change order :arrow_up_down: of any block with CSS [flex+order](https://www.w3schools.com/cssref/css3_pr_order.asp)

```css
/* app/assets/stylesheets/active_admin.css.scss */

#sidebar { display: flex; flex-direction: column; }
#collection_actions_sidebar_section { order: 0; }
#filters_sidebar_section { order: 1; }
.sidebar_section { order: 2; }
```

All modern :new: browsers support this. If your project does not require strong IE9-10 support, then this should do the trick.
